[package]
name = "ctx"
version = "0.1.0"
authors = ["Nikolay Kim <fafhrd91@gmail.com>"]
description = "CTX Library"
readme = "README.md"
keywords = []
homepage = "https://github.com/fafhrd91/ctx"
repository = "https://github.com/fafhrd91/ctx.git"
documentation = "https://fafhrd91.github.io/fafhrd91/ctx/"
categories = ["Asynchronous"]
license = "Apache-2.0"
exclude = [".gitignore", ".travis.yml", ".cargo/config", "appveyor.yml"]

[lib]
name = "ctx"
path = "ctx/lib.rs"

[dependencies]
boxfnonce = "*"

# tokio
bytes = "0.4"
mio = "0.6"
futures = "0.1"
tokio-core = "0.1"
tokio-io = "0.1"

# logging
log = "0.3"

[profile.release]
lto = true
opt-level = 3
debug = true
